# Generated by Django 4.2.6 on 2023-11-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh ", "Arunachal Pradesh "),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu and Kashmir ", "Jammu and Kashmir "),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Chandigarh", "Chandigarh"),
                            ("Dadra and Nagar Haveli", "Dadra and Nagar Haveli"),
                            ("Daman and Diu", "Daman and Diu"),
                            ("Lakshadweep", "Lakshadweep"),
                            (
                                "National Capital Territory of Delhi",
                                "National Capital Territory of Delhi",
                            ),
                            ("Puducherry", "Puducherry"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("election_year", models.IntegerField(default=0)),
                (
                    "election_type",
                    models.CharField(
                        blank=True,
                        choices=[("LS", "Lok Sabha"), ("VS", "Vidhan Sabha")],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VillageMappingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ac_no", models.IntegerField(default=99999, verbose_name="AC No")),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Object Id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Locality"
                    ),
                ),
                (
                    "booth",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Booth"
                    ),
                ),
                (
                    "probable_nearby_vil_voter",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Probable Nearby Village",
                    ),
                ),
                (
                    "mandal",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mandal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VillageLocalityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Data_Analyst.state",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Data_Analyst.villagemappingfile",
                    ),
                ),
            ],
        ),
    ]
