# Generated by Django 4.2.6 on 2023-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Data_Analyst",
            "0002_alter_state_options_alter_villagelocalitymodel_state_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="villagemappingfile",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
