# Generated by Django 4.2.6 on 2023-11-26 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Analyst", "0003_villagemappingfile_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="villagemappingfile",
            name="state",
        ),
    ]
