# Generated by Django 4.2.6 on 2023-11-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Analyst", "0004_remove_villagemappingfile_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="villagemappingfile",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
